# -*- coding: utf-8 -*-
"""motor_losses_characterisation_and_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4Xq4qmC4A-WF-5VJ3n8-7AeIhr0NNBz
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as opt
import math

rho = 1.225 # kg/m^3 # fed from density sensor or whatever...

radius = 0.3048 # m
area = np.pi * radius**2

# Power in Watts (W)
power_W = np.array([
    212.2, 253.5, 296.6, 343.8, 401.8, 460.2, 519.9, 580.2,
    653.4, 724.6, 800.2, 886.2, 958.4, 1048.2, 1153.8, 1230.2,
    1332.1, 1435.8, 1514.0, 1626.5, 1742.3, 2005.6, 2399.0
])

# Thrust in kilograms (kg)
thrust_g = np.array([
    2.416, 2.732, 3.058, 3.377, 3.746, 4.106, 4.419, 4.822,
    5.209, 5.476, 5.947, 6.370, 6.709, 7.086, 7.501, 7.779,
    8.238, 8.654, 9.016, 9.294, 9.782, 10.731, 11.822
])

thrust_N = thrust_g * 9.81  # kg-force to Newtons

# Current in Amperes (A)
current_A = np.array([
    4.6, 5.5, 6.4, 7.4, 8.7, 9.9, 11.2, 12.5,
    14.1, 15.6, 17.3, 19.1, 20.7, 22.6, 24.9, 26.6,
    28.8, 31.0, 32.7, 35.1, 37.6, 43.6, 51.8
])

denom = np.sqrt(2 * rho * area )

R = (power_W - (thrust_N **1.5) / denom) / (current_A **2)

# print(R)
print(f'Mean motor resistance: {np.mean(R):.4f} ohms')
print(f'Median motor resistance: {np.median(R):.4f} ohms')

print("R at each operating point:")
for i, (I, r) in enumerate(zip(current_A, R)):
    print(f"  {I:.1f}A → R = {r:.4f} ohms")

# MULTIVARIATE REGRESSION ANALYSIS

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import pandas as pd
from scipy.optimize import curve_fit
import math

rho = 1.225 # kg/m^3
radius = 0.3048 # m
area = np.pi * radius**2

# Power in Watts (W)
power_W = np.array([
    212.2, 253.5, 296.6, 343.8, 401.8, 460.2, 519.9, 580.2,
    653.4, 724.6, 800.2, 886.2, 958.4, 1048.2, 1153.8, 1230.2,
    1332.1, 1435.8, 1514.0, 1626.5, 1742.3, 2005.6, 2399.0
])

# Speed in Revolutions Per Minute (RPM)
speed_rpm = np.array([
    2455, 2605, 2754, 2900, 3047, 3184, 3325, 3456,
    3589, 3716, 3841, 3959, 4080, 4194, 4307, 4415,
    4519, 4627, 4723, 4821, 4912, 5142, 5442
])

speed_rps = 2* np.pi * (speed_rpm / 60.0)  # RPM to radians per second

# Thrust in kilograms (kg)
thrust_g = np.array([
    2.416, 2.732, 3.058, 3.377, 3.746, 4.106, 4.419, 4.822,
    5.209, 5.476, 5.947, 6.370, 6.709, 7.086, 7.501, 7.779,
    8.238, 8.654, 9.016, 9.294, 9.782, 10.731, 11.822
])

thrust_N = thrust_g * 9.81  # kg-force to Newtons

# Current in Amperes (A)
current_A = np.array([
    4.6, 5.5, 6.4, 7.4, 8.7, 9.9, 11.2, 12.5,
    14.1, 15.6, 17.3, 19.1, 20.7, 22.6, 24.9, 26.6,
    28.8, 31.0, 32.7, 35.1, 37.6, 43.6, 51.8
])

denom = np.sqrt(2 * rho * area )

Power_physics = (thrust_N ** 1.5 ) / denom

LHS = power_W
k_e = 1e-6
k_h = 0.000305

# Temp = 20 # in degrees
# delta_T = Temp - 20 # in degrees
# alpha_copper = 0.00393  # per degree C

def RHS(X, R_copper, k_b, prop_coeff):
    current_A, rps, thrust_N = X  # unpack your two variables
    return R_copper * current_A **2 + k_h * rps * (30.0 /np.pi) + k_e * (rps * 30.0 / np.pi)**2 + k_b * rps + (1/prop_coeff) * (thrust_N ** 1.5 ) / denom

popt, pcov = curve_fit(RHS, (current_A, speed_rps, thrust_N), LHS, p0=(0.050, 1e-7, 0.75), bounds = ([0, 0, 0.6], [1, 0.1, 0.8]))
R_copper, k_b, prop_coeff = popt


print(f"R_copper: {R_copper:.5f} ohms")


print(f"k_b: {k_b:.6e}")
print(f"prop_coeff: {prop_coeff:.6e}")

y_predicted = RHS((current_A, speed_rps, thrust_N), *popt)
residuals = LHS - y_predicted
ss_res = np.sum(residuals**2)
ss_tot = np.sum((LHS - np.mean(LHS))**2)
r2 = 1 - ss_res/ss_tot
print(f"\nR²: {r2:.5f}")
print(f"Max residual: {np.max(np.abs(residuals)):.2f} W")
print(f"Mean residual: {np.mean(np.abs(residuals)):.2f} W")

# INITIAL MODEL TESTING: ACCOUNTED FOR MOTOR AND PROPELLER INEFFICIENCIES

error_array = []
for idx in range(len(current_A)):
  current = current_A[idx]
  RPM = speed_rpm[idx]
  Power_Total = power_W[idx]  # 1048.2W, not 1230.2W
  radpersec = 2* np.pi * (RPM / 60.0)  # RPM to radians per second

  P_loss = R_copper * current**2 + k_h * RPM + k_e * RPM**2 + k_b * radpersec

  Thrust = ( prop_coeff *np.sqrt(2 * rho * area) * (Power_Total - P_loss)) ** 0.667
  Weight = Thrust / 9.81
  error_estimation_percent = (abs(Weight - thrust_g[idx])/thrust_g[idx]) * 100.0
  error_array = np.append(error_array, error_estimation_percent)
  print(f' The estimated weight is {Weight:.4f} kg')
  print(f' The datasheet weight is {thrust_g[idx]:.4f} kg')
  print(f' The error is {error_estimation_percent:.2f} percent')

  # print(f'P_loss: {P_loss:.2f} W')
  # P_ideal = Power_Total - P_loss
  # print(f'P_ideal: {P_ideal:.2f} W')
  print()

print(f'Mean error: {np.mean(error_array):.2f} percent')
print(f'Median error: {np.median(error_array):.2f} percent')

# Pre-Final Model accounting for wind consumption

# T_actual = 7.086 * 9.81  # Newtons
# P_ideal_expected = (T_actual ** 1.5) / denom
# print(f'P_ideal expected: {P_ideal_expected:.2f} W')

# # verify regression at 70% throttle operating point
# idx = 13  # index of 70% throttle point in your arrays
# P_predicted = RHS((current_A[idx:idx+1], speed_rps[idx:idx+1], thrust_N[idx:idx+1]), *popt)
# print(f'P_input actual: {power_W[idx]:.2f} W')
# print(f'P_input predicted by regression: {P_predicted[0]:.2f} W')
# print(f'Residual at this point: {power_W[idx] - P_predicted[0]:.2f} W')

# idx = 13
# I = current_A[idx]
# w = speed_rps[idx]
# T = thrust_N[idx]

# P_copper = R_copper * I**2
# P_iron = k * w**n
# P_bearing = k_b * w
# P_windage = k_w * w**3
# P_aero = (1/prop_coeff) * (T**1.5) / denom

# print(f'P_copper: {P_copper:.2f} W')
# print(f'P_iron: {P_iron:.2f} W')
# print(f'P_bearing: {P_bearing:.2f} W')
# print(f'P_windage: {P_windage:.2f} W')
# print(f'P_aero: {P_aero:.2f} W')
# print(f'Sum: {P_copper+P_iron+P_bearing+P_windage+P_aero:.2f} W')
# print(f'Actual P_input: {power_W[idx]:.2f} W')
# print(f'P_ideal_actuator (no eta): {(T**1.5)/denom:.2f} W')


# idx = 13
# print(f'thrust_N[idx]: {thrust_N[idx]:.4f} N')
# print(f'thrust_g[idx]: {thrust_g[idx]:.4f} kg')
# print(f'denom: {denom:.4f}')
# print(f'P_ideal from array: {(thrust_N[idx]**1.5)/denom:.2f} W')

# # sanity check version
# T_actual = 7.086 * 9.81
# P_ideal_check = (T_actual**1.5)/denom
# print(f'P_ideal from hardcoded: {P_ideal_check:.2f} W')
# print(list(enumerate(thrust_g)))